use actix_web::web;

use crate::handlers;

pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(handlers::health_check)
        .service(handlers::login)
        .service(handlers::register)
        .service(handlers::get_me)
        .service(handlers::patch_me)
        .service(handlers::delete_me)
        .service(handlers::get_me_recetas)
        .service(handlers::get_usuario_publico)
        .service(handlers::listar_ingredientes)
        .service(handlers::listar_tipos_ingrediente)
        .service(handlers::listar_utensilios)
        .service(handlers::listar_tipos_utensilio)
        .service(handlers::listar_recetas)
        .service(handlers::obtener_receta)
        .service(handlers::crear_receta)
        .service(handlers::actualizar_receta)
        .service(handlers::eliminar_receta)
        .service(handlers::subir_imagen_receta)
        .service(handlers::listar_favoritos)
        .service(handlers::agregar_favorito)
        .service(handlers::quitar_favorito)
        .service(handlers::listar_puntuaciones)
        .service(handlers::crear_puntuacion)
        .service(handlers::actualizar_puntuacion)
        .service(handlers::eliminar_puntuacion)
        .service(handlers::listar_grupos)
        .service(handlers::obtener_grupo)
        .service(handlers::crear_grupo)
        .service(handlers::actualizar_grupo)
        .service(handlers::eliminar_grupo)
        .service(handlers::listar_recetas_grupo)
        .service(handlers::agregar_receta_grupo)
        .service(handlers::quitar_receta_grupo)
        .service(handlers::seguir_grupo)
        .service(handlers::dejar_seguir_grupo)
        .service(handlers::listar_seguidores_grupo)
        .service(handlers::listar_logros)
        .service(handlers::listar_mis_logros)
        .service(handlers::reclamar_logro);
}
